### ISSUE TITLE
Issue with aop-ts script 

### ISSUE THREAD

**Issue by PLU12** [scentral/aop-ts3#2]
hi when ever i do /aop then aop i get this error nor can i look at docs due to dead link 

[      script:aop-ts3] Error: Unhandled promise failure: Error: insufficient client permissions
[      script:aop-ts3]     at new Command (/root/FXServer/server/txData/CFXDefault_CABA94.base/resources/[Scripts]/aop-ts3/node_modules/ts3-nodejs-library/lib/transport/Command.js:15:22)
[      script:aop-ts3]     at /root/FXServer/server/txData/CFXDefault_CABA94.base/resources/[Scripts]/aop-ts3/node_modules/ts3-nodejs-library/lib/transport/TeamSpeakQuery.js:79:25
[      script:aop-ts3]     at new Promise (<anonymous>)
[      script:aop-ts3]     at TeamSpeakQuery.handleCommand (/root/FXServer/server/txData/CFXDefault_CABA94.base/resources/[Scripts]/aop-ts3/node_modules/ts3-nodejs-library/lib/transport/TeamSpeakQuery.js:78:16)
[      script:aop-ts3]     at TeamSpeakQuery.execute (/root/FXServer/server/txData/CFXDefault_CABA94.base/resources/[Scripts]/aop-ts3/node_modules/ts3-nodejs-library/lib/transport/TeamSpeakQuery.js:66:21)
[      script:aop-ts3]     at TeamSpeak.execute (/root/FXServer/server/txData/CFXDefault_CABA94.base/resources/[Scripts]/aop-ts3/node_modules/ts3-nodejs-library/lib/TeamSpeak.js:391:31)
[      script:aop-ts3]     at TeamSpeak.channelList (/root/FXServer/server/txData/CFXDefault_CABA94.base/resources/[Scripts]/aop-ts3/node_modules/ts3-nodejs-library/lib/TeamSpeak.js:1684:21)
[      script:aop-ts3]     at TeamSpeak.getChannelById (/root/FXServer/server/txData/CFXDefault_CABA94.base/resources/[Scripts]/aop-ts3/node_modules/ts3-nodejs-library/lib/TeamSpeak.js:863:21)
[      script:aop-ts3]     at @aop-ts3/src/server.js:48:33
[      script:aop-ts3]     at citizen:/scripting/v8/main.js:477:30

**Comment by scentral** [comment]
Support is better offered in our discord! Also docs will be down for a good bit as we are working on a new system
